# version: '3.8'

services:
  chatbot:
    build:
      context: ./services/chatbot
    container_name: gradpilot-chatbot
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      APP_JWT_SECRET: ${JWT_SECRET}

  login-reg:
    build:
      context: ./services/login-reg
    container_name: gradpilot-login-reg
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}

  recommendation:
    build:
      context: ./services/recommendation
    container_name: gradpilot-recommendation
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}

  frontend:
    build:
      context: ./services/frontend
    container_name: gradpilot-frontend
    ports:
      - "80:3000"
    depends_on:
      - chatbot