version: '3.8'
services:
  chatbot:
    build:
      context: ./services/chatbot
    ports:
      - "8081:8081"
    env_file:
      - .env

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    depends_on:
      - chatbot