-- Sample scholarship data for testing
INSERT INTO scholarships (university_id, name, description, apply_link, eligibility, coverage) VALUES
(1, 'MIT Presidential Fellowship', 'Prestigious fellowship for outstanding graduate students at MIT', 'https://gradadmissions.mit.edu/costs-funding/fellowships', 'Exceptional academic record, research potential', 'Full tuition + $40,000 annual stipend'),
(2, 'Stanford Graduate Fellowship', 'Comprehensive funding for Stanford graduate students', 'https://vpge.stanford.edu/fellowships-funding/sgf', 'Outstanding academic achievement, leadership potential', 'Full tuition + $45,000 annual stipend'),
(3, 'Harvard University Fellowship', 'Need-based and merit-based funding for Harvard students', 'https://gsas.harvard.edu/funding', 'Strong academic record, demonstrated need', 'Full tuition + living expenses'),
(4, 'Caltech Graduate Fellowship', 'Fellowship for PhD students in science and engineering', 'https://www.gradoffice.caltech.edu/finances/fellowships', 'Exceptional academic record in STEM fields', 'Full tuition + $36,000 annual stipend'),
(NULL, 'Fulbright Foreign Student Program', 'US government scholarship for international students', 'https://foreign.fulbrightonline.org', 'International students, academic excellence', 'Full tuition + monthly stipend + travel allowance'),
(NULL, 'DAAD EPOS Scholarships', 'German government scholarships for developing countries', 'https://www.daad.de/en/study-and-research-in-germany/scholarships/', 'Citizens of developing countries, relevant work experience', 'Monthly allowance + travel costs + health insurance'),
(NULL, 'Gates Cambridge Scholarship', 'Full-cost scholarship for graduate study at Cambridge', 'https://www.gatescambridge.org/', 'Outstanding intellectual ability, leadership potential', 'Full tuition + maintenance allowance + travel costs'),
(NULL, 'Chevening Scholarships', 'UK government scholarship for emerging leaders', 'https://www.chevening.org/', 'Leadership potential, strong academic background', 'Full tuition + living expenses + travel costs'),
(NULL, 'Commonwealth Scholarship', 'Scholarships for students from Commonwealth countries', 'https://cscuk.fcdo.gov.uk/scholarships/', 'Citizens of Commonwealth countries, academic merit', 'Full tuition + living allowance + travel costs'),
(NULL, 'Erasmus Mundus Joint Master Degrees', 'EU-funded scholarships for international students', 'https://ec.europa.eu/programmes/erasmus-plus/opportunities/individuals/students/erasmus-mundus-joint-master-degrees_en', 'Academic excellence, language requirements', 'Full tuition + monthly allowance + travel costs');
