name: CI/CD

on:
  push:
    branches: [deployment]

permissions:
  contents: read
  packages: write

jobs:
  build-test-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build chatbot
        working-directory: services/chatbot
        run: ./mvnw clean package

      - name: Build login-reg
        working-directory: services/login-reg
        run: ./mvnw clean package

      - name: Build Recommendation
        working-directory: services/recommendation
        run: ./mvnw clean package

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: services/frontend
        run: npm install

      - name: Build frontend
        working-directory: services/frontend
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerize and push recommendation
        working-directory: services/recommendation
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-recommendation:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-recommendation:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-recommendation:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-recommendation:${{ github.sha }}

      - name: Dockerize and push chatbot
        working-directory: services/chatbot
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-chatbot:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-chatbot:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-chatbot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-chatbot:${{ github.sha }}

      - name: Dockerize and push login-reg
        working-directory: services/login-reg
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-login-reg:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-login-reg:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-login-reg:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-login-reg:${{ github.sha }}

      - name: Dockerize and push frontend
        working-directory: services/frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-frontend:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/gradpilot-frontend:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gradpilot-frontend:${{ github.sha }} 

  deploy-to-vm:
    needs: build-test-and-dockerize
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy on Azure VM via SSH 
        uses: appleboy/ssh-action@v1.0.0 
        with:
          host: ${{ secrets.VM_IP}} 
          username: seed 
          key: ${{ secrets.SSH_KEY }} 
          script: | 
            cd /home/seed/GradPilot2/GradPilot
            git pull origin deployment 
            docker compose down 
            docker compose pull
            docker compose up -d
